// <auto-generated />
using System;
using IngressosAppWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IngressosAppWeb.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231214224308_AdicionarCargaInicialCategoria")]
    partial class AdicionarCargaInicialCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoriaIngresso", b =>
                {
                    b.Property<int>("CategoriasCategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("IngressosIngressoId")
                        .HasColumnType("integer");

                    b.HasKey("CategoriasCategoriaId", "IngressosIngressoId");

                    b.HasIndex("IngressosIngressoId");

                    b.ToTable("CategoriaIngresso");
                });

            modelBuilder.Entity("IngressosAppWeb.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("IngressosAppWeb.Models.Ingresso", b =>
                {
                    b.Property<int>("IngressoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngressoId"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoId")
                        .HasColumnType("integer");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("IngressoId");

                    b.HasIndex("TipoId");

                    b.ToTable("Ingresso");
                });

            modelBuilder.Entity("IngressosAppWeb.Models.Tipo", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TipoId");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("CategoriaIngresso", b =>
                {
                    b.HasOne("IngressosAppWeb.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IngressosAppWeb.Models.Ingresso", null)
                        .WithMany()
                        .HasForeignKey("IngressosIngressoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngressosAppWeb.Models.Ingresso", b =>
                {
                    b.HasOne("IngressosAppWeb.Models.Tipo", null)
                        .WithMany("Ingressos")
                        .HasForeignKey("TipoId");
                });

            modelBuilder.Entity("IngressosAppWeb.Models.Tipo", b =>
                {
                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
